version: '3'
services:
  quicrtp:
    build: .
    ports:
      - "5000-5100:5000-5100/udp"
      - "5000-5100:5000-5100/tcp"
      - "4433:4433/udp"
      - "4433:4433/tcp"
    environment:
      - SRTP_KEY=${SRTP_KEY}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
